"""
Content builders: turn a normalized Hire (see hire.py -- either configured
directly via NEW_HIRE_* env vars in create mode, or detected from Deel's
onboarding tracker in scan mode) plus the real Deel/Workspace outcome for
them into a Notion onboarding page (title + markdown body) and a Slack
welcome message.
"""

import logging
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


def build_onboarding_page_title(hire) -> str:
    """Notion page title for the new hire's onboarding doc."""
    return f"{hire.full_name} - Onboarding"


def build_onboarding_page_markdown(
    hire,
    workspace_status: str,
    deel_status: str,
    deel_contract_id: str = "",
) -> str:
    """
    Markdown body for the new hire's Notion onboarding page. Both
    deel_status and workspace_status are short human-readable outcome
    strings (e.g. "Created: contract 34rpznp", "Not provisioned: Google
    Workspace (DWD) is not set up for this workspace yet"), included so the
    doc always reflects what actually happened rather than assuming
    success.
    """
    lines = [
        f"# Welcome, {hire.full_name}!",
        "",
        "## Role Details",
        f"- **Start date:** {hire.start_date}",
        f"- **Title:** {hire.job_title}",
        f"- **Employment type:** {hire.employment_type}",
        f"- **Country:** {hire.country}",
        "",
        "## Accounts & Access",
        f"- **Deel record:** {deel_status}",
        f"- **Google Workspace:** {workspace_status}",
        "",
        "## Onboarding Checklist",
        "- [ ] Complete Deel self-onboarding paperwork",
        "- [ ] Sign in to Google Workspace account and set a password",
        "- [ ] Join core team Slack channels",
        "- [ ] 1:1 with manager in week one",
        "- [ ] Review team documentation and onboarding plan",
        "",
    ]

    if deel_contract_id:
        lines.append(f"_Deel contract ID: {deel_contract_id}_")
        lines.append("")

    lines.append("_Generated by your New Hire Provisioning Agent from a real Deel record._")
    return "\n".join(lines)


def build_welcome_message(hire) -> str:
    """
    Slack welcome message text for the new hire's start, posted to a shared
    team channel (not a DM).
    """
    lines = [f"*Welcome to the team, {hire.full_name}!* :wave:", ""]

    details = []
    if hire.job_title:
        details.append(f"joining as *{hire.job_title}*")
    if hire.start_date:
        details.append(f"starting *{hire.start_date}*")

    if details:
        lines.append(" ".join(details).capitalize() + ".")

    lines.append("")
    lines.append("Please give them a warm welcome when you see them online!")

    return "\n".join(lines)
