
import os
import json
import time
import logging
import requests
from settings import (
    ZENDESK_API_TOKEN, ZENDESK_EMAIL, ZENDESK_SUBDOMAIN,
    SLACK_BOT_TOKEN, SLACK_CHANNEL_ID,
    NOTION_API_KEY, NOTION_KB_DATABASE_ID, LOG_LEVEL,
)
from google.adk.agents import LlmAgent
from google.adk import runners
from google.genai import types as genai_types
import asyncio
from typing import List, Dict, Any
logging.basicConfig(level=LOG_LEVEL)
logger = logging.getLogger("zendesk-slack-notion-agent")

if os.getenv("GOOGLE_ADK_API_KEY") and not os.getenv("GOOGLE_API_KEY"):
    os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_ADK_API_KEY")


STATE_FILE = "state/ticket_thread_map.json"
def load_ticket_thread_map():
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE, "r") as f:
            return json.load(f)
    return {}
def save_ticket_thread_map(mapping):
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w") as f:
        json.dump(mapping, f)
ticket_thread_map = load_ticket_thread_map()



# --- LLM Agent, session, and runner setup ---
LLM_APP_NAME = "zendesk_slack_notion_agent"
LLM_USER_ID = "zendesk"
LLM_SESSION_ID = "suggested_reply"

suggested_reply_agent = LlmAgent(
    model=os.getenv("GOOGLE_ADK_MODEL", "gemini-2.0-flash"),
    name="suggested_reply_agent",
    description="Generates a concise, friendly support reply for a Zendesk ticket.",
    instruction=(
        "You are a helpful support agent. Write only the suggested reply (do not include any explanation, meta-commentary, or bullet points). "
        "The reply should be concise and friendly, ready to send to the customer. "
        "Input will be a JSON object with 'subject' and 'description'. Respond with only the reply text."
    ),
)
_llm_session_service = runners.InMemorySessionService()
try:
    if asyncio.iscoroutinefunction(_llm_session_service.create_session):
        _llm_session = asyncio.run(_llm_session_service.create_session(app_name=LLM_APP_NAME, user_id=LLM_USER_ID, session_id=LLM_SESSION_ID))
    else:
        _llm_session = _llm_session_service.create_session(app_name=LLM_APP_NAME, user_id=LLM_USER_ID, session_id=LLM_SESSION_ID)
except Exception as e:
    _llm_session = None
    logger.exception(f"Failed to create LLM session: {e}")
_llm_runner = runners.Runner(agent=suggested_reply_agent, app_name=LLM_APP_NAME, session_service=_llm_session_service)

# --- Tool functions for the agent ---
def fetch_new_tickets() -> dict:
    url = f"https://{ZENDESK_SUBDOMAIN}.zendesk.com/api/v2/tickets.json?status=new"
    auth = (f"{ZENDESK_EMAIL}/token", ZENDESK_API_TOKEN)
    logger.debug(f"Fetching new tickets from Zendesk: {url}")
    try:
        resp = requests.get(url, auth=auth)
        resp.raise_for_status()
        tickets = resp.json().get("tickets", [])
        logger.debug(f"Fetched {len(tickets)} tickets: {tickets}")
        return {"tickets": tickets}
    except Exception as e:
        logger.exception(f"Error fetching tickets from Zendesk: {e}")
        return {"tickets": []}

def generate_suggested_reply(ticket: dict) -> dict:
    logger.debug(f"Generating suggested reply for ticket: {ticket}")
    try:
        if _llm_runner is None:
            logger.warning("LLM runner not initialized. Returning static reply.")
            return {"suggested_reply": "Thank you for reaching out! We are looking into your issue."}
        user_input = json.dumps({"subject": ticket.get("subject", ""), "description": ticket.get("description", "")})
        content = genai_types.Content(role='user', parts=[genai_types.Part(text=user_input)])
        events = _llm_runner.run(user_id=LLM_USER_ID, session_id=LLM_SESSION_ID, new_message=content)
        reply = None
        for event in events:
            if hasattr(event, 'is_final_response') and event.is_final_response() and event.content:
                reply = event.content.parts[0].text.strip()
                break
        if not reply:
            logger.warning("No reply generated by LlmAgent. Returning static reply.")
            reply = "Thank you for reaching out! We are looking into your issue."
        return {"suggested_reply": reply}
    except Exception as e:
        logger.exception(f"Failed to generate suggested reply with LlmAgent: {e}")
        return {"suggested_reply": "Thank you for reaching out! We are looking into your issue."}

def annotate_tickets_with_replies(tickets: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
            """
            Annotate each ticket with an LLM-generated suggested_reply and return updated tickets.

            Args:
                    tickets (List[Dict[str, Any]]): List of Zendesk ticket dicts.

            OpenAPI schema:
                parameters:
                    tickets:
                        type: array
                        description: List of ticket objects to annotate
                        minItems: 1
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    description: Zendesk ticket ID
                                subject:
                                    type: string
                                    description: Ticket subject
                                description:
                                    type: string
                                    description: Ticket description
                            required:
                                - id
                                - subject
                                - description

            Returns:
                    Dict[str, List[Dict[str, Any]]]: {"tickets": updated_tickets}
            """
            logger.debug(f"Annotating {len(tickets) if tickets else 0} tickets with suggested replies")
            if not tickets:
                    return {"tickets": []}
            updated = []
            for t in tickets:
                    try:
                            reply = generate_suggested_reply(t)
                            t = dict(t)
                            t["suggested_reply"] = reply.get("suggested_reply")
                            updated.append(t)
                    except Exception as e:
                            logger.exception(f"Error annotating ticket {t.get('id')}: {e}")
                            updated.append(t)
            return {"tickets": updated}

# --- Slack API helpers ---
def post_slack_digest(context: dict) -> dict:
    tickets = context.get("tickets", [])
    logger.debug(f"Preparing to post Slack digest for tickets: {tickets}")
    new_tickets = []
    for ticket in tickets:
        ticket_id = str(ticket["id"])
        if ticket_id in ticket_thread_map:
            logger.info(f"Ticket {ticket_id} already posted to Slack digest; skipping.")
            continue
        new_tickets.append(ticket)
    if not new_tickets:
        logger.info("No new tickets for digest; skipping Slack digest.")
        return {"status": "skipped"}
    url = "https://slack.com/api/chat.postMessage"
    headers = {"Authorization": f"Bearer {SLACK_BOT_TOKEN}", "Content-Type": "application/json"}
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": "Daily Support Digest", "emoji": True}},
        {"type": "divider"}
    ]
    for t in new_tickets:
        ticket_url = f"https://{ZENDESK_SUBDOMAIN}.zendesk.com/agent/tickets/{t['id']}"
        subject = t.get('subject', 'No subject')
        status = t.get('status', 'unknown').capitalize()
        desc = t.get('description', '')
        suggested_reply = t.get('suggested_reply', None)
        text = f"*<{ticket_url}|{subject}>*\n*ID:* `{t['id']}`   *Status:* `{status}`\n_{desc}_"
        if suggested_reply:
            text += f"\n>*Suggested reply:* {suggested_reply}"
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": text
            }
        })
        blocks.append({"type": "divider"})
    data = {
        "channel": SLACK_CHANNEL_ID,
        "blocks": blocks,
        "text": "Daily Support Digest"
    }
    logger.debug(f"Posting Slack digest with data: {data}")
    try:
        resp = requests.post(url, headers=headers, json=data)
        resp.raise_for_status()
        logger.info(f"Posted Slack digest. Slack response: {resp.text}")
        for ticket in new_tickets:
            ticket_id = str(ticket["id"])
            ticket_thread_map[ticket_id] = "digest"
        save_ticket_thread_map(ticket_thread_map)
        return {"status": "posted"}
    except Exception as e:
        logger.exception(f"Slack API error: {e}")
        return {"status": "error", "error": str(e)}

# --- Notion API helpers ---
def update_notion_kb(context: dict) -> dict:
    tickets = context.get("tickets", [])
    logger.debug(f"Preparing to update Notion KB for tickets: {tickets}")
    updated = 0
    for ticket in tickets:
        ticket_id = str(ticket["id"])
        if ticket.get('status') == 'solved':
            notion_key = f"notion_{ticket_id}"
            if notion_key in ticket_thread_map:
                logger.info(f"Ticket {ticket_id} already updated in Notion; skipping.")
                continue
            url = "https://api.notion.com/v1/pages"
            headers = {
                "Authorization": f"Bearer {NOTION_API_KEY}",
                "Notion-Version": "2022-06-28",
                "Content-Type": "application/json"
            }
            name = f"Ticket {ticket['id']} - {ticket.get('subject', 'No subject')}"
            status = ticket.get("status", "solved")
            description = ticket.get("description", "")
            resolution = ticket.get("resolution") or "Resolved."
            zendesk_id = str(ticket.get("id", ""))
            zendesk_link = f"https://{ZENDESK_SUBDOMAIN}.zendesk.com/agent/tickets/{zendesk_id}" if zendesk_id else ""
            properties = {
                "Name": {"title": [{"text": {"content": name}}]},
                "status": {"status": {"name": status}},
                "Zendesk Link": {"url": zendesk_link}
            }
            data = {
                "parent": {"database_id": NOTION_KB_DATABASE_ID},
                "properties": properties,
                "children": [
                    {
                        "object": "block",
                        "type": "paragraph",
                        "paragraph": {
                            "rich_text": [
                                {"type": "text", "text": {"content": description}}
                            ]
                        }
                    },
                    {
                        "object": "block",
                        "type": "paragraph",
                        "paragraph": {
                            "rich_text": [
                                {"type": "text", "text": {"content": resolution}}
                            ]
                        }
                    }
                ]
            }
            logger.debug(f"Posting to Notion with data: {data}")
            try:
                resp = requests.post(url, headers=headers, json=data)
                resp.raise_for_status()
                logger.info(f"Updated Notion KB for ticket {ticket['id']}")
                ticket_thread_map[notion_key] = True
                updated += 1
                save_ticket_thread_map(ticket_thread_map)
            except Exception as e:
                logger.exception(f"Notion error response: {e}")
    return {"updated": updated}

# --- Orchestrator LLM Agent ---
ORCH_SESSION_ID = "orchestrator"

orchestrator_agent = LlmAgent(
    model=os.getenv("GOOGLE_ADK_MODEL", "gemini-2.0-flash"),
    name="zendesk_slack_notion_orchestrator",
    description="Orchestrates the Zendesk -> Slack -> Notion pipeline by calling tools in order.",
    instruction=(
        "You are the orchestrator for the support workflow.\n"
        "Steps you must perform in order:\n"
        "1) Call fetch_new_tickets to get a dict with key 'tickets'.\n"
        "2) If there are tickets, call annotate_tickets_with_replies with the list of tickets.\n"
        "3) Call post_slack_digest with the dict containing the updated 'tickets'.\n"
        "4) Call update_notion_kb with the same dict so solved tickets are saved to Notion.\n"
        "If there are no tickets, simply respond that there is nothing to process today."
    ),
    tools=[fetch_new_tickets, annotate_tickets_with_replies, post_slack_digest, update_notion_kb],
)

_orch_session_service = runners.InMemorySessionService()
try:
    if asyncio.iscoroutinefunction(_orch_session_service.create_session):
        _orch_session = asyncio.run(
            _orch_session_service.create_session(
                app_name=LLM_APP_NAME, user_id=LLM_USER_ID, session_id=ORCH_SESSION_ID
            )
        )
    else:
        _orch_session = _orch_session_service.create_session(
            app_name=LLM_APP_NAME, user_id=LLM_USER_ID, session_id=ORCH_SESSION_ID
        )
except Exception as e:
    _orch_session = None
    logger.exception(f"Failed to create orchestrator session: {e}")
_orch_runner = runners.Runner(agent=orchestrator_agent, app_name=LLM_APP_NAME, session_service=_orch_session_service)



def main():
    logger.info("Starting Zendesk + Slack + Notion Google ADK Orchestrated workflow...")
    while True:
        try:
            logger.debug("Starting ADK LlmAgent tool orchestration.")
            user_prompt = "Run the end-to-end support workflow now."
            content = genai_types.Content(role='user', parts=[genai_types.Part(text=user_prompt)])
            events = _orch_runner.run(user_id=LLM_USER_ID, session_id=ORCH_SESSION_ID, new_message=content)
            final_text = None
            for event in events:
                if hasattr(event, 'is_final_response') and event.is_final_response() and event.content:
                    final_text = event.content.parts[0].text.strip()
            if final_text:
                logger.info(f"Orchestrator final answer: {final_text}")
            logger.debug("ADK LlmAgent orchestration loop completed.")
        except Exception as e:
            logger.exception(f"Error in ADK Agent workflow: {e}")
        time.sleep(60)

if __name__ == "__main__":
    main()
